import { LIFECYCLE_STAGES, RESEARCH_TYPES, STANDARDS, getAdaptiveFieldIds, resolveStandards } from "../catalog/index.js";
import { getRequiredFieldIds } from "../validation.js";
import { t } from "../i18n.js";

function element(tag, options = {}, children = []) { const node = document.createElement(tag); const { dataset, ...properties } = options; for (const [key, value] of Object.entries(properties)) { if (value == null) continue; if (key.includes("-")) node.setAttribute(key, value); else node[key] = value; } if (dataset) Object.assign(node.dataset, dataset); for (const child of children) node.append(child); return node; }
function option(value, label, selected) { return element("option", { value, textContent: label, selected }); }
function fieldControl(id, state, required, locale) { const label = element("label", { className:`field-control${["topic","problemStatement","researchQuestion","existingInformation","resourcesTimeline","eligibilityCriteria","informationSources"].includes(id) ? " wide" : ""}`, dataset:{ fieldId:id } }); const text = element("span", { textContent:t(locale, `fields.${id}`) }); if (required) text.append(element("span", { className:"required-marker", textContent:" *" })); const control = element(["topic","problemStatement","researchQuestion","existingInformation","resourcesTimeline","eligibilityCriteria","informationSources"].includes(id) ? "textarea" : "input", { id:`field-${id}`, name:id, value:state.fields[id] ?? "", dataset:{ fieldId:id }, required }); if (control.tagName === "TEXTAREA") control.rows = 3; label.append(text, control); return label; }

export function focusFirstBlockingIssue(preflight) { const issue = preflight.blocking.find(item => item.fieldId); const control = issue && document.querySelector(`[data-field-id="${issue.fieldId}"] input, [data-field-id="${issue.fieldId}"] textarea, [data-field-id="${issue.fieldId}"] select`); control?.focus(); return Boolean(control); }

export function renderWorkspace(root, state, preflight) {
  const locale = state.interfaceLocale; root.querySelectorAll("[data-i18n]").forEach(node => { node.textContent = t(locale, node.dataset.i18n); }); root.querySelector("#interfaceLanguage").value = locale;
  const setup = root.querySelector("#setupBar"); const researchType = element("select", { id:"researchType", dataset:{ action:"research-type" } }, RESEARCH_TYPES.map(type => option(type.id, t(locale, `researchTypes.${type.id}`), type.id === state.researchTypeId))); const evidenceMode = element("select", { dataset:{ action:"evidence-mode" } }, ["planning","uploaded","web-research"].map(id => option(id, t(locale, `evidenceModes.${id}`), id === state.evidenceMode))); const outputLanguage = element("select", { dataset:{ action:"output-language" } }, ["thai","english","bilingual"].map(id => option(id, t(locale, `outputLanguages.${id}`), id === state.outputLanguage))); setup.replaceChildren(element("div", { className:"panel-kicker", textContent:t(locale,"setup") }), element("div", { className:"setup-controls" }, [element("label", { className:"control-label", textContent:t(locale,"researchType") }, [researchType]), element("label", { className:"control-label", textContent:t(locale,"evidenceMode") }, [evidenceMode]), element("label", { className:"control-label", textContent:t(locale,"outputLanguage") }, [outputLanguage])]));
  const rail = root.querySelector("#lifecycleRail"); rail.replaceChildren(element("div", { className:"rail-heading", textContent:t(locale,"lifecycle") }), ...LIFECYCLE_STAGES.map(stage => element("button", { type:"button", className:`stage-button${stage.id === state.stageId ? " active" : ""}`, dataset:{ action:"stage", stageId:stage.id }, "aria-current":stage.id === state.stageId ? "step" : null }, [element("span", { className:`stage-dot ${preflight.readinessByStage[stage.id]}` }), element("span", { className:"stage-label", textContent:t(locale,`stages.${stage.id}`) })])));
  const ids = getAdaptiveFieldIds(state.researchTypeId, state.stageId); const required = new Set(getRequiredFieldIds(state.researchTypeId,state.stageId)); const main = root.querySelector("#workspaceMain"); const selectedStage = LIFECYCLE_STAGES.find(stage => stage.id === state.stageId); const form = element("form", { className:"adaptive-form", noValidate:true }); ids.forEach(id => form.append(fieldControl(id,state,required.has(id),locale))); const issues = preflight.blocking.filter(issue => issue.fieldId); main.replaceChildren(element("div", { className:"form-heading" }, [element("div", {}, [element("div", { className:"panel-kicker", textContent:t(locale,`stages.${state.stageId}`) }), element("h2", { textContent:t(locale,`researchTypes.${state.researchTypeId}`) }), element("p", { className:"form-description", textContent:selectedStage.task })])]), form, element("section", { className:"validation-summary", "aria-label":t(locale,"validation") }, [element("h3", { textContent:t(locale,"validation") }), issues.length ? element("ul", { className:"validation-list" }, issues.map(issue => element("li", { textContent:t(locale,issue.messageKey) }))) : element("p", { className:"empty-note", textContent:t(locale,"noIssues") })]));
  const applicable = resolveStandards(state.researchTypeId,state.stageId); const typeStandards = STANDARDS.filter(standard => standard.researchTypes.includes(state.researchTypeId)); const summary = root.querySelector("#standardsSummary"); summary.replaceChildren(element("section", { className:"summary-section" }, [element("h2", { textContent:t(locale,"standards") }), element("ul", { className:"summary-list" }, typeStandards.map(standard => element("li", { textContent:standard.version }, [element("small", { textContent:standard.name })]))) ]), element("section", { className:"summary-section" }, [element("h2", { textContent:t(locale,"stageMatch") }), applicable.length ? element("ul", { className:"summary-list" }, applicable.map(standard => element("li", { textContent:standard.version }))) : element("p", { className:"empty-note", textContent:t(locale,"noStageStandard") })]));
  root.querySelector("#promptDrawerRoot").replaceChildren(element("div", { className:"drawer-placeholder", textContent:t(locale,"promptPlaceholder") }));
}

export function renderConfirmation(root, labels, locale) { const dialogRoot = root.querySelector("#dialogRoot"); dialogRoot.replaceChildren(element("div", { className:"dialog-backdrop" }, [element("section", { className:"dialog", role:"dialog", "aria-modal":"true", "aria-labelledby":"confirmTitle" }, [element("h2", { id:"confirmTitle", textContent:t(locale,"confirmTitle") }), element("p", { textContent:t(locale,"confirmText") }), element("ul", {}, labels.map(label => element("li", { textContent:label }))), element("div", { className:"dialog-actions" }, [element("button", { type:"button", className:"secondary-button", dataset:{ action:"cancel-type-change" }, textContent:t(locale,"cancel") }), element("button", { type:"button", className:"primary-button", dataset:{ action:"confirm-type-change" }, textContent:t(locale,"confirm") })])]) ])); }
export function clearConfirmation(root) { root.querySelector("#dialogRoot").replaceChildren(); }
